
// Objective-C API for talking to the following Go packages
//
//	github.com/imperviousinc/hnsq/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __MobileHNS_FRAMEWORK_H__
#define __MobileHNS_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Universe.objc.h"

#endif
