// Objective-C API for talking to dnsext Go package.
//   gobind -lang=objc dnsext
//
// File is generated by gobind. Do not edit.

#ifndef __Dnsext_H__
#define __Dnsext_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class DnsextServer;

@interface DnsextServer : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)listenAddr dohServer:(NSString* _Nullable)dohServer;
- (void)closeIdleConnections;
- (void)listenAndServe;
- (void)shutdown;
@end

FOUNDATION_EXPORT void DnsextCloseIdleConnections(void);

FOUNDATION_EXPORT long DnsextInitServer(NSString* _Nullable l, NSString* _Nullable doh);

FOUNDATION_EXPORT void DnsextListenAndServe(void);

FOUNDATION_EXPORT DnsextServer* _Nullable DnsextNewServer(NSString* _Nullable listenAddr, NSString* _Nullable dohServer, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void DnsextShutdown(void);

#endif
