
// Objective-C API for talking to the following Go packages
//
//	dnsext
//
// File is generated by gomobile bind. Do not edit.
#ifndef __DNSExt_FRAMEWORK_H__
#define __DNSExt_FRAMEWORK_H__

#include "Dnsext.objc.h"
#include "Universe.objc.h"

#endif
